AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  GetToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/get.handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref TokenTable
  AddToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/add.handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: put
      Environment:
        Variables:
          TABLE_NAME: !Ref TokenTable

  TokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_IMAGE